
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mitloxjcltirxejqtyzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pdGxveGpjbHRpcnhlanF0eXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTA5MTYsImV4cCI6MjA1ODY2NjkxNn0.RBMXsnr1POqiH2eUk-B1fa4qyLE0KMeQRz4DbNiVdec";

// Create and configure the Supabase client with essential options
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,  // Use localStorage for persistence
    persistSession: true,   // Keep session between page refreshes
    autoRefreshToken: true  // Automatically refresh token before expiry
  }
});
